name: PR Checks

on:
  pull_request:
    branches: [develop, release]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22.15.0'

      - name: Install dependencies
        run: |
          node --version
          npm --version
          rm -f package-lock.json
          npm install --loglevel verbose

      - name: Run tests
        run: npm test
